In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r'data\train.csv')
df.shape

(404290, 6)

In [3]:
new_df = df.sample(3000)

In [4]:
new_df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [5]:
new_df.duplicated().sum()

np.int64(0)

In [6]:
ques_df = new_df[['question1','question2']]
ques_df.head()

,question1,question2
20490,How do I find a good girlfriend?,Why is it hard to get a girlfriend?
5133,Is dating fun? Should it be?,Is dating actually fun?
131141,What are the pros and cons of San Francisco Ba...,What are the pros and cons of San Francisco Ba...
200540,What's our purpose of life in this world?,Wanna ask someone please. What is life? And wh...
25384,What is the best way to serve Chianti?,What IIMs could I expect calls from?

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

# merge texts
questions = list(ques_df['question1']) + list(ques_df['question2'])

cv = CountVectorizer(max_features=3000)

q1_arr, q2_arr = np.vsplit(cv.fit_transform(questions).toarray(),2)

In [8]:
temp_df1 = pd.DataFrame(q1_arr, index= ques_df.index)
temp_df2 = pd.DataFrame(q2_arr, index= ques_df.index)
temp_df = pd.concat([temp_df1, temp_df2], axis=1)
temp_df.shape

(3000, 6000)

In [9]:
temp_df

,0,1,2,3,4,5,6,7,8,9,...,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999
20490,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5133,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
131141,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
200540,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25384,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85627,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96667,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40773,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2722,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
337060,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
temp_df['is_duplicate'] = new_df['is_duplicate']

In [11]:
temp_df.head()

,0,1,2,3,4,5,6,7,8,9,...,2991,2992,2993,2994,2995,2996,2997,2998,2999,is_duplicate
20490,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5133,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
131141,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
200540,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
25384,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(temp_df.iloc[:,0:-1].values,temp_df.iloc[:,-1].values,test_size=0.2,random_state=1)

In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7116666666666667

In [14]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train,y_train)
y_pred = xgb.predict(X_test)
accuracy_score(y_test,y_pred)

0.6816666666666666